### ISSUE TITLE
You should learn to code

### ISSUE THREAD

**Issue by disclearing** [GaMeIsNtOvEr/KnockbackFFA#3]
Learn to do a basic for loop

**Comment by Mmd4J** [comment]
tyty

**Comment by Mmd4J** [comment]
this repo is too old no one've forced you to read that while its dead

**Comment by disclearing** [comment]
Simply just learn to code you skid

**Comment by Mmd4J** [comment]
nvm prev comment had child abuse content. simply touch some grass

**Comment by Mmd645** [comment]
> Simply just learn to code you skid

Who tf do you think you are?
No namer dog hhhhhhhh
Consider Killing yourself

**Comment by disclearing** [comment]
> > Simply just learn to code you skid
> 
> Who tf do you think you are? No namer dog hhhhhhhh Consider Killing yourself

dam i hurt you

**Comment by disclearing** [comment]
> nvm prev comment had child abuse content. simply touch some grass

child abuse dam imagine being a nonce

**Comment by Mmd4J** [comment]
> child abuse dam imagine being a nonce

go to the gym and lose some weights instead of complaining about inactive projects thats all i meant.i dont care about what you say tbh. werent you expecting me to react like "daaaam bros a leaker" right? seriously  injecting virus into plugins is what you're proud of? what a shame.

**Comment by disclearing** [comment]
> > child abuse dam imagine being a nonce
> 
> go to the gym and lose some weights instead of complaining about inactive projects thats all i meant.i dont care about what you say tbh. werent you expecting me to react like "daaaam bros a leaker" right? seriously injecting virus into plugins is what you're proud of? what a shame.

First the kid in my github is someone I doxed 2 a virus you are aware I leak source code right ? but you completely ignored being a nonce gg go next

**Comment by Mmd4J** [comment]
> > > child abuse dam imagine being a nonce
> > 
> > 
> > go to the gym and lose some weights instead of complaining about inactive projects thats all i meant.i dont care about what you say tbh. werent you expecting me to react like "daaaam bros a leaker" right? seriously injecting virus into plugins is what you're proud of? what a shame.
> 
> First the kid in my github is someone I doxed 2 a virus you are aware I leak source code right ? but you completely ignored being a nonce gg go next

I totally believe on you. :+1:
